version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    
    environment:
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/zookeeper-3.4.13/conf/zookeeper_server_jaas.conf"
      SERVER_JVMFLAGS: "-Djava.security.auth.login.config=/opt/zookeeper-3.4.13/conf/zookeeper_server_jaas.conf"
    
    volumes:
      - ./kafka-settings/to-zookeeper/:/opt/zookeeper-3.4.13/conf/:rw
      
        
    
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # There is the env. variable KAFKA_SERVER_IP in the case of deploying on the server
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://${KAFKA_SERVER_IP:-localhost}:9092
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka_server_jaas.conf"
      
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN

    depends_on:
      - zookeeper
    volumes:
      - ./kafka-settings/to-kafka-broker/:/opt/kafka/config/:rw

