export const GET_USER_SET_INVALIDATE = 'GET_USER_SET_INVALIDATE';

export const SAVE_IMAGE_PREVIEW = 'SAVE_IMAGE_PREVIEW';
export const SAVE_MAP_PREVIEW = 'SAVE_MAP_PREVIEW';

export const LOAD_MAP_SUCCESS = 'LOAD_MAP_SUCCESS';
export const LOAD_MAP_START = 'LOAD_MAP_START';
export const LOAD_MAP_FAIL = 'LOAD_MAP_FAIL';

export const LOAD_AREAS_SUCCESS = 'LOAD_AREAS_SUCCESS';
export const LOAD_AREAS_START = 'LOAD_AREAS_START';
export const LOAD_AREAS_ERROR = 'LOAD_AREAS_ERROR';
export const CLEAR_AREAS = 'CLEAR_AREAS';
export const DELETE_AREA = 'DELETE_AREA';
export const ADD_AREA_REF = 'ADD_AREA_REF';

export const LOAD_AREAS_INFO_SUCCESS = 'LOAD_AREAS_INFO_SUCCESS';
export const LOAD_AREAS_INFO_START = 'LOAD_AREAS_INFO_START';
export const LOAD_AREAS_INFO_ERROR = 'LOAD_AREAS_INFO_ERROR';
export const SAVE_OVERLAY = 'SAVE_OVERLAY';
export const SAVE_PROJECTION = 'SAVE_PROJECTION';
export const SAVE_MAP = 'SAVE_MAP';
export const SET_SIZE = 'SET_SIZE';

export const LOAD_SCALE_SUCCESS = 'LOAD_SCALE_SUCCESS';
export const LOAD_SCALE_START = 'LOAD_SCALE_START';
export const LOAD_SCALE_ERROR = 'LOAD_SCALE_ERROR';
export const LOAD_IMAGE_SIZE = 'LOAD_IMAGE_SIZE';
export const LOAD_IMAGE_SIZE_START = 'LOAD_IMAGE_SIZE_START';
export const LOAD_IMAGE_SIZE_SUCCESS = 'LOAD_IMAGE_SIZE_SUCCESS';
export const LOAD_MAP_DONE = 'LOAD_MAP_DONE';

export const BUILDINGS_DID_INVALIDATE = 'BUILDINGS_DID_INVALIDATE';

export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';

export const UPDATE_USER_AVATAR = 'UPDATE_USER_AVATAR';

export const SET_BUILDING_FORM_FIELD = '@@redux-form/CHANGE';
export const SET_BUILDING_FORM_CURRENTSTEP = 'SET_BUILDING_FORM_CURRENTSTEP';

export const SET_READER_NAMES = 'SET_READER_NAMES';
