beacons:
  sso:
    registeredRedirectUri: https://bcn.lab.epam.com/api/v1/login
    userAuthorizationUri: https://bcn.lab.epam.com/api/v1/oauth/authorize

spring.data.mongodb:
  host: ecse0050040f.epam.com
  port: 32217

eureka:
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO

swagger:
  cors:
    allowedOrigins: https://bcn.lab.epam.com, http://localhost:3000
  host: bcn.lab.epam.com
