version: '2.2'
services:
  config-service:
    build:
      context: .
      dockerfile: docker/beacon-cloud-config-service.Dockerfile
    container_name: config-service
    restart: always
    network_mode: host
#    healthcheck:
#      test: ["CMD", "lsof", "-i:10100"]
#      interval: 30s
#      timeout: 10s
#      retries: 50
  registry-service:
    build:
      context: .
      dockerfile: docker/beacon-cloud-registry-service.Dockerfile
    container_name: registry-service
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-i:10005"]
      interval: 30s
      timeout: 10s
      retries: 50
  gateway:
    build:
      context: .
      dockerfile: docker/beacon-cloud-gateway.Dockerfile
    container_name: gateway-service
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-i:10020"]
      interval: 30s
      timeout: 10s
      retries: 50
  uaa-service:
    build:
      context: .
      dockerfile: docker/beacon-cloud-uaa-service.Dockerfile
    container_name: uaa-service
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-i:10035"]
      interval: 30s
      timeout: 10s
      retries: 50
  mongo:
    build:
      context: .
      dockerfile: docker/beacon-cloud-mongo.Dockerfile
    volumes:
      - "/data/db:/data/db"
    container_name: mongo
    network_mode: host
  setting-service:
    build:
      context: .
      dockerfile: docker/beacon-cloud-setting-service.Dockerfile
    container_name: setting-service
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "lsof", "-i:10050"]
      interval: 30s
      timeout: 10s
      retries: 50
  building-service:
    build:
      context: .
      dockerfile: docker/beacon-cloud-building-service.Dockerfile
    network_mode: host
    restart: always
    container_name: building-service
    healthcheck:
      test: ["CMD", "lsof", "-i:10040"]
      interval: 30s
      timeout: 10s
      retries: 50
  admin-web:
    build:
      context: .
      dockerfile: docker/beacon-admin-web.Dockerfile
    network_mode: host
    container_name: admin-web


