spring:
  kafka:
    property:
      bootstrap.servers: ECSE00500096.epam.com:9092
      zookeeper.server: ECSE00500096.epam.com:2181
    consumer:
      bootstrap-servers: ECSE00500096.epam.com:9092
