spring:
  cloud:
    config:
      server:
        git:
          search-paths:
            - spec/config/default
            - spec/config/dev

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    root: INFO
